version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:9.5
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        env_file:
            - docker.env
        networks:
            - vntrip
        restart: always
    redis:
        container_name: redis
        image: redis:alpine
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - ./data/redis:/data
        ports:
            - '6379:6379'
        networks:
            - vntrip
        restart: always

networks:
    vntrip:
        driver: bridge
